# Generated by Django 3.0.5 on 2024-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productmst_productsubcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcat',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
