# Generated by Django 5.0 on 2024-01-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usersignup',
            new_name='user_register',
        ),
    ]
